services:
  postgres:
    image: postgres:15
    container_name: devpulse-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devpulse_local
    ports:
      - "5433:5432"
    volumes:
      - devpulse_data:/var/lib/postgresql/data

volumes:
  devpulse_data: 