import { parseGithubUrl } from '../../utils/parseGithubUrl.js'
import { checkRepoExists, checkIssueExists } from '../../github/repoValidator.js'
import { pullData } from '../../github/pullData.js'
import { fetchIssue } from '../../github/fetchIssue.js'
import { createDebugIssue, createAgentStep, updateDebugIssueStatus } from '../../db/issue.js'
import { findOrCreateRepo } from '../../db/repo.js'
import { agentLoop } from '../../agent/agentLoop.js'
import { createPR } from '../../github/createPR.js'
import { reviewPR } from './prReview.js'
import ora from 'ora'
import chalk from 'chalk'

export async function solveCommand(issueUrl: string, options: { branch: string }) {
    try {
        if (!issueUrl) return console.log("❌ Issue URL is missing")
        if (!options) return console.log("❌ Options are missing")

        const { owner, repo, issueNumberStr } = parseGithubUrl(issueUrl)

        const repoSpinner = ora('Checking repository...').start()
        const repoexit = await checkRepoExists(owner, repo)
        if (!repoexit) return repoSpinner.fail('Repo not found')
        repoSpinner.succeed(`Repo ${owner}/${repo} found`)

        const issueSpinner = ora('Checking issue...').start()
        const isusseExit = await checkIssueExists(issueUrl)
        if (!isusseExit) return issueSpinner.fail('Issue not found')
        issueSpinner.succeed(`Issue #${issueNumberStr} found`)

        const pullSpinner = ora('Cloning/pulling repository...').start()
        const dataPull = await pullData({ owner, repo })
        if (!dataPull) return pullSpinner.fail('Failed to pull repo')
        pullSpinner.succeed('Repository ready')

        const repoRecord = await findOrCreateRepo(repo, dataPull.loaclpath)
        if (!repoRecord) return console.log('❌ Failed to save repo to database')

        const fetchSpinner = ora('Fetching issue details...').start()
        const isussData = await fetchIssue({ owner, repo, issueNumber: issueNumberStr })
        if (!isussData) return fetchSpinner.fail('Failed to fetch issue')
        fetchSpinner.succeed(`Issue: ${isussData.title}`)

        const createDebugIssues = await createDebugIssue({ 
            title: isussData.title, 
            repositoryId: repoRecord.id 
        })
        if (!createDebugIssues) return console.log('❌ Failed to create debug issue')

        const agentSpinner = ora('Running AI agent...').start()
        const loopResult = await agentLoop({
            issueUrl,
            title: isussData.title,
            body: isussData.body,
            repoOwner: owner,
            repoName: repo,
            issueNumber: parseInt(issueNumberStr),
            localPath: dataPull.loaclpath,
            diff: dataPull.diff,
            commits: dataPull.commits
        })

        if (loopResult.passed) {
            await updateDebugIssueStatus(createDebugIssues.id, 'solved')
            agentSpinner.succeed('Issue solved!')
        } else {
            await updateDebugIssueStatus(createDebugIssues.id, 'failed')
            agentSpinner.fail('Could not solve issue')
            return
        }

        await createAgentStep({
            debugIssueId: createDebugIssues.id,
            thought: loopResult.aiThought ?? 'Analyzing issue and codebase',
            actionTaken: 'Sent context to AI',
            gitDiff: dataPull.diff,
            outputLog: loopResult.finalOutput,
            stepNumber: 1
        })

        // Build PR body
        const filesSection = (loopResult.writtenFiles ?? []).length > 0
            ? (loopResult.writtenFiles ?? []).map(f => `- \`${f}\``).join('\n')
            : '- No files tracked'

        const prBody = `## 🤖 DevPulse AI Agent — Automated Fix

### 📋 Issue Summary
**Title:** ${isussData.title}
**Closes:** #${issueNumberStr}

### 🔍 Root Cause Analysis
${loopResult.aiThought || 'AI analyzed the codebase and identified the root cause.'}

### 🛠️ Files Changed
${filesSection}

### 🔄 Agent Performance
${(loopResult.attempts ?? 1) === 1 ? '✅ Fixed on first attempt' : `🔄 Required ${loopResult.attempts} attempts to pass all tests`}

### ✅ Verification
- Fix was applied in an isolated sandbox environment
- All existing tests passed before opening this PR
- No unrelated files were modified

### ⚠️ Important
Please review the changes carefully before merging.

---
*Generated by [DevPulse](https://github.com/kirtikumarAlone/devpulse-core) — AI-powered GitHub issue solver*`

        // Ask user to review PR before submitting
        const review = await reviewPR({
            title: `fix: resolve issue #${issueNumberStr}`,
            body: prBody,
            issueNumber: issueNumberStr,
            writtenFiles: loopResult.writtenFiles ?? []
        })

        if (!review.confirmed) {
            console.log(chalk.yellow('\n❌ PR cancelled by user.'))
            return
        }

        const prSpinner = ora('Creating Pull Request...').start()
        const prUrl = await createPR(
            owner,
            repo,
            issueNumberStr,
            dataPull.loaclpath,
            review.title,
            loopResult.writtenFiles ?? [],
            review.body,
            loopResult.attempts ?? 1
        )
        prSpinner.succeed(`PR created: ${prUrl}`)

    } catch (error) {
        console.log(error)
    }
}